/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package Enums;

/**
 *
 * @author dudum
 */
public enum Autores {
    ANÓNIMO, CHINUA_ACHEBE, HANS_CHRISTIAN_ANDERSEN, DANTE_ALIGHIERI, JANE_AUSTEN, HONORÉ_DE_BALZAC, SAMUEL_BECKETT, GIOVANNI_BOCCACCIO, JORGE_LUIS_BORGES, EMILY_BRONTË, ALBERT_CAMUS, PAUL_CELAN, LOUIS_FERDINAND_CÉLINE, MIGUEL_DE_CERVANTES, GEOFFREY_CHAUCER, ANTÓN_CHÉJOV, JOSEPH_CONRAD, CHARLES_DICKENS, DENIS_DIDEROT, ALFRED_DÖBLIN, FIÓDOR_DOSTOIEVSKI, GEORGE_ELIOT, RALPH_ELLISON, EURÍPIDES, WILLIAM_FAULKNER, GUSTAVE_FLAUBERT, FEDERICO_GARCÍA_LORCA, GABRIEL_GARCÍA_MÁRQUEZ, JOHANN_WOLFGANG_VON_GOETHE, NIKOLAI_GOGOL, GÜNTER_GRASS, JOÃO_GUIMARÃES_ROSA, KNUT_HAMSUN, ERNEST_HEMINGWAY, HOMERO, HENRIK_IBSEN, JAMES_JOYCE, FRANZ_KAFKA, KĀLIDĀSA, YASUNARI_KAWABATA, NIKOS_KAZANTZAKIS, D_H_LAWRENCE, HALLDÓR_LAXNESS, GIACOMO_LEOPARDI, DORIS_LESSING, ASTRID_LINDGREN, LU_XUN, NAGUIB_MAHFUZ, THOMAS_MANN, HERMAN_MELVILLE, MICHEL_DE_MONTAIGNE, ELSA_MORANTE, TONI_MORRISON, MURASAKI_SHIKIBU, ROBERT_MUSIL, VLADIMIR_NABOKOV, GEORGE_ORWELL, OVIDIO, FERNANDO_PESSOA, EDGAR_ALLAN_POE, MARCEL_PROUST, FRANÇOIS_RABELAIS, JUAN_RULFO, RUMI, SALMAN_RUSHDIE, SAADI, TAYEB_SALIH, JOSÉ_SARAMAGO, WILLIAM_SHAKESPEARE, SÓFOCLES, STENDHAL, LAURENCE_STERNE, ITALO_SVEVO, JONATHAN_SWIFT, LEV_TOLSTÓI, MARK_TWAIN, VALMIKI, VIRGILIO, VIASA, WALT_WHITMAN, VIRGINIA_WOOLF, MARGUERITE_YOURCENAR;
}
