/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package Enums;

/**
 *
 * @author dudum
 */
public enum TitulosLibro {
    
    POEMA_DE_GILGAMESH, LIBRO_DE_JOB, LAS_MIL_Y_UNA_NOCHES, SAGA_DE_NJÁL, TODO_SE_DESMORONA, CUENTOS_INFANTILES, DIVINA_COMEDIA, ORGULLO_Y_PREJUICIO, PAPÁ_GORIOT, MOLLOY, MALONE_MUERE, EL_INNOMBRABLE, UNA_TRILOGÍA, DECAMERÓN, FICCIONES, CUMBRES_BORRASCOSAS, EL_EXTRANJERO, POEMAS, VIAJE_AL_FIN_DE_LA_NOCHE, DON_QUIJOTE_DE_LA_MANCHA, LOS_CUENTOS_DE_CANTERBURY, RELATOS_CORTOS, NOSTROMO, GRANDES_ESPERANZAS, JACQUES_EL_FATALISTA, BERLIN_ALEXANDERPLATZ, CRIMEN_Y_CASTIGO, EL_IDIOTA, LOS_ENDEMONIADOS, LOS_HERMANOS_KARAMAZOV, MIDDLEMARCH, EL_HOMBRE_INVISIBLE, MEDEA, ABSALOM_ABSALOM, EL_RUIDO_Y_LA_FURIA, MADAME_BOVARY, LA_EDUCACIÓN_SENTIMENTAL, ROMANCERO_GITANO, CIEN_AÑOS_DE_SOLEDAD, EL_AMOR_EN_LOS_TIEMPOS_DEL_CÓLERA, FAUSTO, ALMAS_MUERTAS, EL_TAMBOR_DE_HOJALATA, GRAN_SERTÓN_VEREDAS, HAMBRE, EL_VIEJO_Y_EL_MAR, ILÍADA, ODISEA, CASA_DE_MUÑECAS, ULISES, RELATOS_CORTOS2, EL_PROCESO, EL_CASTILLO, SHAKUNTALA, EL_SONIDO_DE_LA_MONTAÑA, ZORBA, EL_GRIEGO, HIJOS_Y_AMANTES, GENTE_INDEPENDIENTE, POEMAS2, EL_CUADERNO_DORADO, PIPPI_CALZASLARGAS, DIARIO_DE_UN_LOCO, HIJOS_DE_NUESTRO_BARRIO, LOS_BUDDENBROOK, LA_MONTAÑA_MÁGICA, MOBY_DICK, ENSAYOS, LA_HISTORIA, BELOVED, GENJI_MONOGATARI, EL_HOMBRE_SIN_ATRIBUTOS, LOLITA, MIL_NUEVE_OCHENTA_Y_CUATRO, LAS_METAMORFOSIS, LIBRO_DEL_DESASOSIEGO, CUENTOS, EN_BUSCA_DEL_TIEMPO_PERDIDO, GARGANTÚA_Y_PANTAGRUEL, PEDRO_PÁRAMO, MASNAVI, HIJOS_DE_LA_MEDIANOCHE, BOSTAN, TIEMPO_DE_MIGRAR_AL_NORTE, ENSAYO_SOBRE_LA_CEGUERA, HAMLET, EL_REY_LEAR, OTELO, EDIPO_REY, ROJO_Y_NEGRO, VIDA_Y_OPINIONES_DEL_CABALLERO_TRISTRAM_SHANDY, LA_CONCIENCIA_DE_ZENO, LOS_VIAJES_DE_GULLIVER, GUERRA_Y_PAZ, ANA_KARENINA, LA_MUERTE_DE_IVÁN_ILICH, LAS_AVENTURAS_DE_HUCKLEBERRY_FINN, RAMAYANA, ENEIDA, MAHABHÁRATA, HOJAS_DE_HIERBA, LA_SEÑORA_DALLOWAY, AL_FARO, MEMORIAS_DE_ADRIANO;
}
